### ISSUE TITLE
対話型のときに構文エラーが表示されない

### ISSUE THREAD

**Issue by torus** [torus/42-minishell#129]

**Comment by torus** [comment]
@JUNNETWORKS エラーメッセージはどうやってだせばいいでしょう？
`-c` のときは `	put_err_msg("Parse error.");` を呼んでいるだけのようなんですが、これに加えて `g_shell.status` を 1 にすればいいですかね？

**Comment by JUNNETWORKS** [comment]
@torus そうですね. `g_shell.status = 1` という風にすれば `$?` に値がセットされます.
