### ISSUE TITLE
`cat | ls` を実行時に bash と同じ挙動になるようにする

### ISSUE THREAD

**Issue by JUNNETWORKS** [torus/42-minishell#31]
`cat | ls` をbashで実行した時, `ls` の実行結果が表示された後, `cat` の標準入力待ちが始まる.

これ即ちbashのパイプはコマンドを順番に実行するのではなく, ただ単にパイプで入手出力をプロセス間でつなぐだけのようだ.

また, `cat`標準入力待ちの状態で Ctrl+C (SIGINT) を押しても `$?` が0になることから, `$?` には最後のコマンドの終了ステータスが入るようだ.

**Comment by torus** [comment]
うんうん。パイプはプロセスを並列で走らせます。`cat | grep x` とかを試してみると分かりやすいかも。

**Comment by JUNNETWORKS** [comment]
#70 このプルリクエストで修正された.

![image](https://user-images.githubusercontent.com/26608037/116630275-f7ee3b00-a98d-11eb-9e6c-45f2834dff51.png)
