### ISSUE TITLE
ASTをコマンド実行のための構造体に変換する

### ISSUE THREAD

**Issue by JUNNETWORKS** [torus/42-minishell#32]

**Comment by JUNNETWORKS** [comment]
@torus ASTの構造は以下のようになるという認識なのですが正しいでしょうか？

![image](https://user-images.githubusercontent.com/26608037/115348229-54629500-a1ed-11eb-9636-0ac345325ad1.jpeg)

また、'string_node->next'が￼￼使われるケースが想像出来ないのですが、例があれば教えていただきたいです

**Comment by torus** [comment]
はい、そんな感じです！

`string_node->next` は、たとえば `abc"def"'ghi'`のようにクォートの種類の違う文字列が連続するときに使います。
この場合、`abc` と `"def"` と `'ghi'` の 3 個のトークンですが、結合後には 1 個の引数になります。クォートの種類によって変数の展開方法が変わるので、AST の段階ではこれらを区別しています。
ただ、いまの段階ではまだクォートされた文字列をパースできないので出番がないです。

**Comment by JUNNETWORKS** [comment]
@torus parserに関するテストを見る感じ, arguments に対する自分の認識が間違っているのかな と思いました.

argumentsというのは `string_node` か `redirection_node` のどちらか1つしか値が入っていないという認識で正しいでしょうか?

自分の認識を図にすると以下の様になります. (最初の図から変更したところは黄色く塗ってます)

![image](https://user-images.githubusercontent.com/26608037/115542992-dcbf6380-a2db-11eb-8c96-898a29f8f1cc.png)

**Comment by torus** [comment]
あ、すみません、そうですね。
```
**arguments ::=
**		redirection
**	  | redirection arguments
**	  | string
**	  | string arguments
```
↑このように定義しているので、どちらか一方しか入りません。

**Comment by JUNNETWORKS** [comment]
なるほど!! 理解出来ました. ありがとうございます!
