### ISSUE TITLE
シグナルハンドラ

### ISSUE THREAD

**Issue by torus** [torus/42-minishell#37]
子プロセスを起動するところで設定する。

**Comment by JUNNETWORKS** [comment]
対応する必要のあるシグナル

- SIGINT (ctrl-C)
- SIGQUIT(ctrl-\)

**Comment by JUNNETWORKS** [comment]
詳解UNIXプログラミング 10章(シグナル) と 18章(端末入出力) が参考になりそう

**Comment by JUNNETWORKS** [comment]
SIGINT
- bash: `^C` という文字を表示して改行
- 子プロセス: 終了してシェル(bash)に戻る

SIGQUIT
- bash: 特に何も起きないし表示されない.
- 子プロセス: `^\` と表示されてその後`Quit (core dumped)`と表示され, 子プロセスは終了し, シェル(bash)に戻る

![image](https://user-images.githubusercontent.com/26608037/116635267-49e88e00-a999-11eb-9494-3ba2036faa45.png)

**Comment by JUNNETWORKS** [comment]
`^C` や `^\` が表示されるのは特に何もしなくても端末から入力される.

逆に `^\` を表示させない方が難しいかも知れない

**Comment by JUNNETWORKS** [comment]
Bash公式実装の [sig.c](https://github.com/bminor/bash/blob/master/sig.c#L98) が参考になりそう

**Comment by JUNNETWORKS** [comment]
シグナルで終了したコマンドの終了コードは `last_command_exit_value = 128 + sig;` となる.

SIGINT(=2)で終了した場合は終了コードは130になる.

**Comment by JUNNETWORKS** [comment]
![Uploading image.png…]()

**Comment by JUNNETWORKS** [comment]
![image](https://user-images.githubusercontent.com/26608037/116647765-4fa09c80-a9b6-11eb-9658-0684a7b9e7e7.png)

**Comment by JUNNETWORKS** [comment]
`exec()` された場合, **`exec()`を読んだプロセスがシグナルを無視していない限り**, 普通, 全てのシグナルの動作をデフォルト動作に変更する.
