### ISSUE TITLE
コマンド実行時の環境変数(expandable)の展開

### ISSUE THREAD

**Issue by JUNNETWORKS** [torus/42-minishell#42]
環境変数をどのタイミングで展開するか迷いどころ.

ASTの構築が完了しコマンドを実行形式(`t_command_invocation`)に変換するときか, `execvp()`を呼ぶ直前か

**Comment by JUNNETWORKS** [comment]
https://discord.com/channels/761086132959838258/762313539414261821/833325930348675073

環境変数の展開は、parse後、コマンド実行の直前にやっておくといいと思います。

parseの段階でやってしまうと、以下のようなケースで対応できないかもしれません。
```
export A=hello; echo $A; export A=42; echo $A
hello
42
```

bashの処理の流れは、以下のドキュメントのp54 図3.1: Bashのコンポーネントのアーキテクチャが参考になると思います。
http://m-takagi.github.io/aosa-ja/aosa.pdf

**Comment by torus** [comment]
あ、#27 がこれのつもりでした。展開は `t_command_invocation` を作る段階でやっておく必要があります。変数の展開後にスペースが含まれている処理が必要なんですが、これはコマンドの引数の場合とリダイレクトのファイル名の場合で必要な処理が変わります。

たとえば、`$A="ABC DEF"` のとき、単に `$A` というコマンドラインの場合は、`abc` というコマンドと `def` という引数に展開されますが、`echo > $A` のときにはエラーを発生させる必要があります。

**Comment by torus** [comment]
![bash-expansion](https://user-images.githubusercontent.com/65044/115355567-c0e19200-a1f5-11eb-981b-05531137b474.png)
この赤く囲んだところが mandatory の部分です。

**Comment by torus** [comment]
#27 からコピー：
![image](https://user-images.githubusercontent.com/65044/114675281-05c37f80-9d43-11eb-8980-335c01d6f207.png)

**Comment by JUNNETWORKS** [comment]
理解できました! ありがとうございます!

![image](https://user-images.githubusercontent.com/26608037/115366010-dfe52180-a1ff-11eb-9393-003409b1de21.png)

**Comment by JUNNETWORKS** [comment]
メモ
![image](https://user-images.githubusercontent.com/26608037/115768644-8c342d00-a3e5-11eb-8a61-42d40277e83c.png)

**Comment by JUNNETWORKS** [comment]
![image](https://user-images.githubusercontent.com/26608037/115773558-6f025d00-a3eb-11eb-95c7-703779ffc877.png)

**Comment by JUNNETWORKS** [comment]
> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit.
https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html

環境変数で使える文字

**Comment by JUNNETWORKS** [comment]
[Allowed characters in Linux environment variable names](https://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names) が参考になる.

IEEEの仕様では以下のようになっている
> These strings have the form name=value; names shall not contain the character '='. For values to be portable across systems conforming to IEEE Std 1003.1-2001, the value shall be composed of characters from the portable character set (except NUL and as indicated below). There is no meaning associated with the order of strings in the environment. If more than one string in a process' environment has the same name, the consequences are undefined.
> 
> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names. Uppercase and lowercase letters shall retain their unique identities and shall not be folded together. The name space of environment variable names containing lowercase letters is reserved for applications. Applications can define any environment variables with names from this name space without modifying the behavior of the standard utilities.
https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html

使用可能な文字は基本的は 大文字, 小文字, 数字, アンダーバー という感じ. 一応シェルの実装によってはそれ以外の文字を許可することもできるけど, あんまり考えなくて良さそう?
システム(OS)側で定義されている環境変数は大文字と数字とアンダーバーのみで構成されている.
小文字を含む環境変数はアプリケーション用に予約されている.
