### ISSUE TITLE
組み込みコマンド

### ISSUE THREAD

**Issue by torus** [torus/42-minishell#46]
- [x] echo `-n` オプション
- [x] cd
- [x] pwd
- [x] export
- [x] unset
- [x] env
- [x] exit

**Comment by JUNNETWORKS** [comment]
`cd` は詳解UNIXプログラミング4.23に良さそうな例が載ってる. `chdir` を使えばよさそう.

`pwd` は`getcwd`使えば良いかな.

**Comment by JUNNETWORKS** [comment]
`help export`

> export: export [-fn] [name[=value] ...] or export -p
>     Set export attribute for shell variables.
> 
>     Marks each NAME for automatic export to the environment of subsequently
>     executed commands.  If VALUE is supplied, assign VALUE before exporting.
> 
>     Options:
>       -f        refer to shell functions
>       -n        remove the export property from each NAME
>       -p        display a list of all exported variables and functions
> 
>     An argument of `--' disables further option processing.
> 
>     Exit Status:
>     Returns success unless an invalid option is given or NAME is invalid.
>

**Comment by JUNNETWORKS** [comment]
`environ` に新しい環境変数を追加する時にmallocしてヒープ領域に移動させるのだが, 2回目以降だとメモリリークを防ぐために free が必要になる. しかし, どうやって environ が heap 領域にあるかどうか判定する?

プログラムロード時のメモリマップでは環境変数はプロセスのメモリマップの中でもっとも高位なアドレスに存在しているので, ローカル変数のメモリアドレスと比較することで環境変数がヒープ領域にいるかどうかが判定できる. (画像は 詳解UNIXプログラミング より)

![image](https://user-images.githubusercontent.com/26608037/116778553-860d1300-aaad-11eb-859f-4ecac016beb4.png)


実際に `environ` が初期状態ではスタック領域より高位のアドレスに存在することは以下のプログラムを実行することで見ることが出来る.

```c
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>

extern char **environ;

int main()
{
    char stack;
    char *heap = malloc(sizeof(char));
    printf("environ: %p\n", environ);
    printf("stack:   %p\n", &stack);
    printf("heap:    %p\n", heap);
}
```

実行すると

```
environ: 0x7fffa8b562f8
stack:   0x7fffa8b561df
heap:    0x55910a53c2a0
```

実際に画像のように配置されていることがわかる.

**Comment by JUNNETWORKS** [comment]
ビルトインコマンドのテスト用プログラム

```c
#include "builtin.h"

/*
 * gcc main_builtin.c builtin*.c cmd_status.c env*.c libft/libft.a
 */
int main(int argc, char **argv)
{
	if (argc <= 1)
	{
		printf("argc must be larger than 1\n");
		return (1);
	}
	printf("is_builtin_command: %d\n", is_builtin_command(argv[1]));
	int status = get_builtin_func(argv[1])(argv + 1);
	printf("status: %d\n", status);
	return (0);
}
```

**Comment by JUNNETWORKS** [comment]
`export` で出てくる `declare -x hoge=hoge` の `declare -x` って環境変数として宣言されてるという意味なのか

[【 declare 】コマンド――変数を宣言する、変数などの内容を表示する](https://www.atmarkit.co.jp/ait/articles/1905/30/news017.html)

![image](https://user-images.githubusercontent.com/26608037/116801087-88b94800-ab41-11eb-92fd-cb5b3f06c47a.png)

**Comment by JUNNETWORKS** [comment]
改めて何を実装する必要があるのか整理

- [echo](https://www.atmarkit.co.jp/ait/articles/1705/26/news013.html):  `-n` オプションの対応のみでOK.
  - `-n`オプションは最後の改行なしというオプション.
- [cd](https://www.atmarkit.co.jp/ait/articles/1712/14/news021.html): 絶対パス, 相対パスでカレントディレクトリを移動できるようにすればOK. オプションについては何も書いてないけど対応しなくても良いという認識.
- [pwd](https://www.atmarkit.co.jp/ait/articles/1712/14/news021.html): オプションや引数の対応は必要ない.
  - オプションや引数の対応は必要ないということは, ただ単純にカレントディレクトリの絶対パスを標準出力に出力すればよい. 
- [export](https://www.atmarkit.co.jp/ait/articles/1801/12/news015.html): オプション対応は必要ない.
  - `export` が引数無しで実行された場合は環境変数一覧を表示する.
  - `export ABC` とした場合には環境変数を設定するが, 値はセットされていない.
  - 既に値が設定されている環境変数`ABC="abc"`に対して, `export ABC` とした場合には特に何もしない.
  - `export ABC="ABC"` とした場合には値が設定された環境変数を設定する. 既に値が存在していた場合には上書きする.
- [unset](https://www.atmarkit.co.jp/ait/articles/1905/24/news015.html): オプション対応は必要ない.
  - 引数で指定された環境変数を削除する. 指定された環境変数が存在していないくても別にエラーにならない.
- [env](https://www.atmarkit.co.jp/ait/articles/1801/18/news016.html): オプションや引数の対応は必要ない.
  - envコマンドは本来環境変数を設定し, プログラムを実行するコマンドだが, 今回はオプションや引数の対応はしなくて良いので, 単純に環境変数を出力するだけでよい.
  - ただし, `key=value`のように値が設定された環境変数のみを出力する.
  - ![image](https://user-images.githubusercontent.com/26608037/116810373-685bae80-ab7e-11eb-82bb-719f7066ba7c.png)
- [exit](https://www.gnu.org/software/bash/manual/bash.html#Shell-Builtin-Commands): オプションの対応は必要ない.
  - `exit [n]` という引数を取り, シェルを終了し終了コードに`n`を設定する.
  - `exit` の出力は標準エラー出力に出力されることに注意.
  - ![image](https://user-images.githubusercontent.com/26608037/116810283-ef5c5700-ab7d-11eb-9a1c-2b0f2b5300aa.png)

**Comment by JUNNETWORKS** [comment]
`export` で実際に `environ` に環境変数が追加されるのは`key=value` (valueは空文字列でもOK) を受け取ったときだけっぽい.

```c
/* test_environ.c */
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>

extern char **environ;

int main()
{
	for(int i = 0; environ[i]; i++)
	{
		
		char *keyname = strndup(environ[i], strchr(environ[i], '=') - environ[i]);
		printf("%s: %p\n", keyname, environ[i]);
		free(keyname);
	}
}
```

![image](https://user-images.githubusercontent.com/26608037/116820931-73303680-abb2-11eb-9201-e9c7ff629d78.png)

**Comment by JUNNETWORKS** [comment]
ビルトインコマンドは単体で実行する時は親プロセスで実行, パイプの時は子プロセスで実行する.

以下の`export` の動きがわかりやすい例.
![image](https://user-images.githubusercontent.com/26608037/116906107-ca014300-ac7a-11eb-95d8-d36380649082.png)

`export HOGE="abc" | echo $HOGE` の場合, `export` は子プロセスで実行されており, 親プロセスの環境変数は変更されない.

逆に `export HOGE="abc"` のようにパイプなしの場合, 親プロセスで実行されるので親プロセスの環境変数が変更され, その後のコマンドから参照できる.

**Comment by JUNNETWORKS** [comment]
`chdir("/bin")` を実行した時に `/usr/bin` に移動してしまうのだが, これは `/bin -> /usr/bin` のようなシンボリックリンクだからであり, `chdir()` はシンボリックリンクを辿るのでこのような挙動になる.

![image](https://user-images.githubusercontent.com/26608037/116923750-f6748980-ac91-11eb-8fe3-ecb7c963d125.png)
