### ISSUE TITLE
リダイレクションの環境変数展開を実装する

### ISSUE THREAD

**Issue by JUNNETWORKS** [torus/42-minishell#62]
リダイレクションに環境変数が渡されていた場合, コマンドの引数の場合と少し違う挙動をするので別Issueを立てた.

**Comment by JUNNETWORKS** [comment]
#27 からコピー：
![image](https://user-images.githubusercontent.com/65044/114675281-05c37f80-9d43-11eb-8980-335c01d6f207.png)

_Originally posted by @torus in https://github.com/torus/42-minishell/issues/42#issuecomment-823048679_

**Comment by JUNNETWORKS** [comment]
あ、#27 がこれのつもりでした。展開は `t_command_invocation` を作る段階でやっておく必要があります。変数の展開後にスペースが含まれている処理が必要なんですが、これはコマンドの引数の場合とリダイレクトのファイル名の場合で必要な処理が変わります。

たとえば、`$A="ABC DEF"` のとき、単に `$A` というコマンドラインの場合は、`abc` というコマンドと `def` という引数に展開されますが、`echo > $A` のときにはエラーを発生させる必要があります。

_Originally posted by @torus in https://github.com/torus/42-minishell/issues/42#issuecomment-823042722_

**Comment by JUNNETWORKS** [comment]
![image](https://user-images.githubusercontent.com/26608037/115789957-e989a780-a400-11eb-89c8-c6e731afae43.png)

パースの時点でエラーとなっているっぽくて, そもそもコマンド実行がされない(リダイレクトで指定されたファイルが作られてない)

**Comment by JUNNETWORKS** [comment]
![image](https://user-images.githubusercontent.com/26608037/115791157-ea233d80-a402-11eb-807a-557df14792bb.png)

環境変数の値が空文字列の場合もエラー

**Comment by JUNNETWORKS** [comment]
![image](https://user-images.githubusercontent.com/26608037/115791247-150d9180-a403-11eb-8959-ac12b5d38f07.png)

環境変数が存在しない場合もエラー

**Comment by JUNNETWORKS** [comment]
環境変数が空文字列
![image](https://user-images.githubusercontent.com/26608037/115791644-c1e80e80-a403-11eb-9b97-b1f816fdade1.png)

---

環境変数が存在しない
![image](https://user-images.githubusercontent.com/26608037/115791709-e3e19100-a403-11eb-975d-9fb52d582b17.png)

---

環境変数にスペースが含まれている
![image](https://user-images.githubusercontent.com/26608037/115791808-0f647b80-a404-11eb-82b4-39848872978f.png)

---

環境変数にリダイレクト記号がある
![image](https://user-images.githubusercontent.com/26608037/115791875-2f943a80-a404-11eb-872c-7e1fb3834072.png)

---

リダイレクトの途中でスペース区切りの環境変数が入っている
![image](https://user-images.githubusercontent.com/26608037/115791986-6d915e80-a404-11eb-900a-33451ea98a86.png)

**Comment by JUNNETWORKS** [comment]
ASTからcmdinvoに変換するタイミングか, リダイレクトで指定された各ファイルのopen失敗したタイミングでエラーを返すかがわからん...

**Comment by JUNNETWORKS** [comment]
ダブルクオーテーションで囲むと正しく動く.
![image](https://user-images.githubusercontent.com/26608037/115792576-7df60900-a405-11eb-99f1-c5872fa6d72a.png)

本当にどこでエラーを判定すればよいのだ...

**Comment by torus** [comment]
最初にぼくがイメージしていた動作は次のようなものです。これで多分ひととおりカバーできていると思うんですが、ダメなケースはありますかね？

### 共通の動作

- 変数展開は `TOKTYPE_EXPANDABLE` と `TOKTYPE_EXPANDABLE_QUOTED` に対してのみ行います。
  - 変数がセットされていないときは単なる空文字列に展開します。
- その次に展開済みの `TOKTYPE_EXPANDABLE` に対して ft_split をして、空白が含まれていれば複数の引数に分割します。`TOKTYPE_EXPANDABLE_QUOTED` に対しては split してはいけないことに注意してください。

例：`$A="a b"` のとき
`x$A"y z"` は次のトークン列になります：

- EXPANDABLE (`x$A`)
- EXPANDABLE_QUOTED (`y z`)

次に EXPANDABLE の中に `$` が含まれているので、展開します。すると次のようになります：

- EXPANDABLE (`xa b`)
- EXPANDABLE_QUOTED (`y z`)

さらに、EXPANDABLE について空白で区切ります。すると 1 個目の EXPANDABLE が 2 個に別れて、最後の要素は次の `y z` とくっつきます：

- `xa`
- `by z`

`y z` は QUOTED なので、split はしないことに注意してください。

これにより、最終的に 2 個の引数列に展開されます。

### リダイレクト先の処理

- 展開後の引数の数がちょうど 1 個でない場合（ゼロまたは複数のとき）：
  「曖昧なリダイレクト」のエラー
- 展開結果がちょうど 1 個のときはファイルをオープンして、失敗したらエラー

**Comment by torus** [comment]
ちなみに、変数の展開はパースのあとで行われるので、`>` などの文字も特別扱いはしません。

```
$ export A='>'
$ echo $A
>
$ echo hello > $A
$ ls
'>'
$ cat '>'
hello
$ 
```

**Comment by JUNNETWORKS** [comment]
> 最初にぼくがイメージしていた動作は次のようなものです。これで多分ひととおりカバーできていると思うんですが、ダメなケースはありますかね？
> 
> ### 共通の動作
> * 変数展開は `TOKTYPE_EXPANDABLE` と `TOKTYPE_EXPANDABLE_QUOTED` に対してのみ行います。
>   
>   * 変数がセットされていないときは単なる空文字列に展開します。
> * その次に展開済みの `TOKTYPE_EXPANDABLE` に対して ft_split をして、空白が含まれていれば複数の引数に分割します。`TOKTYPE_EXPANDABLE_QUOTED` に対しては split してはいけないことに注意してください。
> 
> 例：`$A="a b"` のとき
> `x$A"y z"` は次のトークン列になります：
> 
> * EXPANDABLE (`x$A`)
> * EXPANDABLE_QUOTED (`y z`)
> 
> 次に EXPANDABLE の中に `$` が含まれているので、展開します。すると次のようになります：
> 
> * EXPANDABLE (`xa b`)
> * EXPANDABLE_QUOTED (`y z`)
> 
> さらに、EXPANDABLE について空白で区切ります。すると 1 個目の EXPANDABLE が 2 個に別れて、最後の要素は次の `y z` とくっつきます：
> 
> * `xa`
> * `by z`
> 
> `y z` は QUOTED なので、split はしないことに注意してください。
> 
> これにより、最終的に 2 個の引数列に展開されます。
> 
> ### リダイレクト先の処理
> * 展開後の引数の数がちょうど 1 個でない場合（ゼロまたは複数のとき）：
>   「曖昧なリダイレクト」のエラー
> * 展開結果がちょうど 1 個のときはファイルをオープンして、失敗したらエラー

以下のケースの場合, 上記のロジックだと上手く行かないと思います.

`$ABC=" a b "` で, 入力が `$ABC"c d"`. この時出力は

- `a`
- `b`
- `c d`

のようになるはずですが, ひさしさんのおっしゃってたロジックだと

- `a`
- `bc d`

のようになると思います.

**Comment by torus** [comment]
おお確かに。ft_split する時に、文字列の先頭と末尾が空白でないか確かめる必要がありますね。
