### ISSUE TITLE
エスケープされたクオーテーションが処理できない

### ISSUE THREAD

**Issue by JUNNETWORKS** [torus/42-minishell#63]
`echo hoge$ABC"hoge \\\"hoge"'$ABC' \n` という入力が処理できていなさそうなので, 修正お願いしたいです. (自分のテストケースのコードが間違っている可能性ももちろんあるのですが)

```c
		t_parse_buffer	buf;
		init_buf_with_string(&buf, "echo hoge$ABC\"hoge \\\"hoge\"'$ABC' \n");
		t_token	tok;

		lex_get_token(&buf, &tok);

		t_parse_ast *node = parse_command(&buf, &tok);
```

**Comment by torus** [comment]
エスケープのことはすっかり忘れてました。
テストコードはあってると思います。
シングルクォート中のエスケープも必要ですね。

**Comment by torus** [comment]
ちょっと試してみたところ、シングルクオート内のエスケープは処理しなくてよさそうでした。
