### ISSUE TITLE
`-c` オプションの実装

### ISSUE THREAD

**Issue by JUNNETWORKS** [torus/42-minishell#65]
`-c` を実装すると他の方が作ってくれたテスターが使えるようになるので, 実装すると良さそう.

**Comment by JUNNETWORKS** [comment]
@torus こちらお願いしてもよろしいでしょうか?

**Comment by torus** [comment]
いいですよ。

**Comment by JUNNETWORKS** [comment]
ありがとうございます!

**Comment by JUNNETWORKS** [comment]
minishellのテスター

- [42_minishell_tester](https://github.com/nafuka11/42_minishell_tester)
