### ISSUE TITLE
一度何かしらのコマンドを実行しないとEOFに反応しない

### ISSUE THREAD

**Issue by JUNNETWORKS** [torus/42-minishell#74]
![image](https://user-images.githubusercontent.com/26608037/116646382-dbb0c500-a9b2-11eb-93d5-6f4863aaae9b.png)

ctrl-D を押しても `parse error.` が出るだけでプロンプトが終了しない. でも, 何かしらのコマンドが実行された後だと終了する.

**Comment by JUNNETWORKS** [comment]
@torus こちら確認していただいてもよろしいでしょうか?

**Comment by torus** [comment]
現状だとコマンド行エディタが動いていないので、入力のところは termcap の対応ができたら入れ替えます。

**Comment by JUNNETWORKS** [comment]
なるほど! 了解しました!
