### ISSUE TITLE
エスケープ (`\$USER` とか) に対応する

### ISSUE THREAD

**Issue by JUNNETWORKS** [torus/42-minishell#84]

**Comment by torus** [comment]
あ、これ、レキサーの方で対応します。レキサーの段階でないと `abc\ def` のようなパターンが扱えないので。
なので、変数の展開のところでは `\` を木にせずに `$` を見つけたらかならず展開するようにしてください。

**Comment by torus** [comment]
`\$abc` のときは、`$` が展開されないように `'$'abc` として読み込むようにしておきます。そうすれば後続の処理は変更しなくても大丈夫ですよね？

**Comment by JUNNETWORKS** [comment]
> `\$abc` のときは、`$` が展開されないように `'$'abc` として読み込むようにしておきます。そうすれば後続の処理は変更しなくても大丈夫ですよね？

はい！問題ないと思います！それでお願いします！

**Comment by torus** [comment]
担当者をかえておきました。
